//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.formapagtopedido = new HashSet<formapagtopedido>();
            this.pedidoitem = new HashSet<pedidoitem>();
        }
    
        public int Id { get; set; }
        public string obs { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> desconto { get; set; }
        public Nullable<decimal> totalliquido { get; set; }
        public string situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formapagtopedido> formapagtopedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoitem> pedidoitem { get; set; }
    }
}
