//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoitem
    {
        public int Id { get; set; }
        public Nullable<int> fkpedido { get; set; }
        public string fkitem { get; set; }
        public Nullable<int> quatidade { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual item item { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
